### ISSUE TITLE
Not showing variants for speakers

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#16]
The reader is not displaying variants for speakers, as in poem 1: `<sp who="#Corydon">
                        <speaker>
                            <app>
                                <lem wit="#G #P #A #φ" source="#Ulit. #Wernsd. #GlaeserSqq">C.</lem>
                                <rdg wit="#N #π #χ" source="#p"/>
                                <rdg wit="#ε #β #γ #μ #ρ" source="#eddAnteGlaeser">O.</rdg>
                            </app>
                        </speaker>`

**Comment by hcayless** [comment]
I've fixed this. In order to keep the app buttons visible and usable when there's a version that omits the label though, I've had to set a fixed height for the speaker tag. I think this is fine in general, but it makes me wonder if any of these are cases where there's something deeper going on and we really want to model whether or not the speaker has changed, for example. This would be variance in the `<sp>` rather than the label...
