### ISSUE TITLE
Exclude and Require not working at 2.71

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#22]
I have tried a number of ways of encoding Burman's conjectures at 2.71 using exclude and require to get their partners to show up as expected, but none of the options I have tried is working. It works at 1.8–9, but not at 1.68, 2.71, or any other place where the swap happens on a single line. This appears to be a bug relating to swaps within the same line.

**Comment by hcayless** [comment]
This should work now, but it will mean switching the source back to using `@require`, which I think is best suited to this use case (it's using `@exclude`) now. I've fixed it in my local copy to test, but I've also been working on re-formatting the XML source, because it's gotten too messy for my taste. That will entail changing basically every line in the document though, so I don't want to commit it until you give me the all-clear.

**Comment by sjhuskey** [comment]
Go for it. Yes, it's pretty messy.
